import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { TheHeader } from '@/components/TheHeader/TheHeader'
import { TheFooter } from '@/components/TheFooter/TheFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Practic Next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TheHeader />
        <main className='container-main'>{children}</main>
        <TheFooter />
      </body>
    </html>
  )
}
